services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/boatapp-postgres
      - SPRING_DATASOURCE_USERNAME=boatapp-postgres
      - SPRING_DATASOURCE_PASSWORD=hunter2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=boatapp-postgres
      - POSTGRES_PASSWORD=hunter2

